-- Rename google_chat_webhook to discord_webhook to reflect the change
ALTER TABLE users 
RENAME COLUMN google_chat_webhook TO discord_webhook;

-- Add a check constraint to ensure it looks like a discord webhook
ALTER TABLE users ADD CONSTRAINT check_discord_webhook CHECK (discord_webhook LIKE 'https://discord.com/api/webhooks/%' OR discord_webhook IS NULL);

-- Create error_logs table for tracking failed alerts
CREATE TABLE IF NOT EXISTS error_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    stock_symbol TEXT,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for error_logs (Users can see their own errors)
ALTER TABLE error_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own error logs" 
ON error_logs FOR SELECT 
USING (auth.uid() = user_id); -- Assuming auth.uid matches user_id logic, adjust if needed

