-- ⚠️ DESTRUCTIVE ACTION: Resets the entire public schema
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

-- Grant usage (standard Supabase setup)
GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;

-- 1. PROFILES Table (Extends auth.users)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  discord_webhook TEXT CHECK (discord_webhook LIKE 'https://discord.com/api/webhooks/%' OR discord_webhook IS NULL),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. STOCKS Table
CREATE TABLE public.stocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  symbol TEXT NOT NULL,
  buy_price DECIMAL(10, 2) NOT NULL,
  quantity INTEGER DEFAULT 1,
  profit_alert_pct DECIMAL(5, 2) DEFAULT 5.0,
  loss_alert_pct DECIMAL(5, 2) DEFAULT 5.0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_alert_sent TIMESTAMPTZ,
  notes TEXT
);

-- 3. ALERTS Table (History)
CREATE TABLE public.alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stock_id BIGINT REFERENCES public.stocks(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  alert_type TEXT NOT NULL, -- 'profit' or 'loss'
  current_price DECIMAL(10, 2),
  threshold_price DECIMAL(10, 2),
  atp_price DECIMAL(10, 2),
  percentage_change DECIMAL(5, 2),
  is_acknowledged BOOLEAN DEFAULT FALSE,
  acknowledged_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Error Logs
CREATE TABLE public.error_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  stock_symbol TEXT,
  error_message TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.error_logs ENABLE ROW LEVEL SECURITY;

-- Policies --

-- Profiles
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Stocks
CREATE POLICY "Users can view own stocks" ON public.stocks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own stocks" ON public.stocks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own stocks" ON public.stocks FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own stocks" ON public.stocks FOR DELETE USING (auth.uid() = user_id);

-- Alerts
CREATE POLICY "Users can view own alerts" ON public.alerts FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own alerts (acknowledge)" ON public.alerts FOR UPDATE USING (auth.uid() = user_id);
-- Scraper (Service Role) needs to insert alerts. Service Role bypasses RLS, so no specific policy needed for it.

-- Error Logs
CREATE POLICY "Users can view own errors" ON public.error_logs FOR SELECT USING (auth.uid() = user_id);

-- Functions --

-- Trigger to create profile on signup (Optional but recommended)
-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, discord_webhook)
  values (
    new.id, 
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'discord_webhook'
  );
  return new;
end;
$$;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Helper Function: should_send_alert
CREATE OR REPLACE FUNCTION should_send_alert(
  p_stock_id BIGINT,
  p_alert_type TEXT
) RETURNS BOOLEAN AS $$
DECLARE
  unacknowledged_alert_id BIGINT;
BEGIN
  SELECT id INTO unacknowledged_alert_id
  FROM public.alerts
  WHERE stock_id = p_stock_id
    AND alert_type = p_alert_type
    AND is_acknowledged = FALSE
  LIMIT 1;
  
  RETURN unacknowledged_alert_id IS NULL;
END;
$$ LANGUAGE plpgsql;
